on:
  pull_request:
    types: [synchronize]

name: Check version

jobs:
  checkVersion:
    name: Check version
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: workflow-settings.json
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
      - uses: actions/checkout@v2
      - name: Set running flag
        run: |
          if [[ ! -f readme.txt ]]; then
            echo "::set-env name=RUNNING::"
          fi

      - name: Get version
        uses: technote-space/get-next-version-action@v1
        with:
          EXCLUDE_MESSAGES: ${{ env.EXCLUDE_MESSAGES }}
        if: env.RUNNING
      - name: Check package version
        uses: technote-space/wp-version-check-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH_PREFIX: release/
          NEXT_VERSION: ${{ env.NEXT_VERSION }}
        if: env.NEXT_VERSION
