on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "!*"

name: Build

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - name: Install Package dependencies
        run: composer prepare:js
      - name: Check code style
        run: composer eslint
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci && bash travis-ci/bin/prepare.sh
        env:
          CI: 1
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
      - name: Install Composer dependencies
        run: composer prepare:php
      - name: Check code style
        run: composer phpcs
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci && bash travis-ci/bin/prepare.sh
        env:
          CI: 1
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
      - name: Install Composer dependencies
        run: composer prepare:php
      - name: Check code style
        run: composer phpmd
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  jest:
    name: Jest
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - name: Install Package dependencies
        run: composer prepare:js
      - name: Run tests
        run: composer jest
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
  phpunit:
    name: PHPUnit
    needs: [phpcs, phpmd]
    runs-on: ubuntu-16.04
    services:
      mysql:
        image: mysql
        ports:
          - 3306
    strategy:
      matrix:
        php: ['7.0', '7.3', '5.6']
        WP_VERSION: ['latest', '5.2', '5.0']
        WP_MULTISITE: ['0', '1']
        include:
          - php: '7.3'
            WP_VERSION: 'latest'
            WP_MULTISITE: '1'
            ACTIVATE_POPULAR_PLUGINS: 1
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - name: Switch PHP version
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: sudo ln -sf "/usr/bin/php$PHP_VERSION" /etc/alternatives/php
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci && bash travis-ci/bin/prepare.sh
        env:
          CI: 1
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
          WP_VERSION: ${{ matrix.WP_VERSION }}
          ACTIVATE_POPULAR_PLUGINS: ${{ matrix.ACTIVATE_POPULAR_PLUGINS }}
      - name: Run tests
        run: bash travis-ci/bin/php/wp-test.sh
        env:
          CI: 1
          DB_PASS: root
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
          WP_VERSION: ${{ matrix.WP_VERSION }}
          WP_MULTISITE: ${{ matrix.WP_MULTISITE }}
          ACTIVATE_POPULAR_PLUGINS: ${{ matrix.ACTIVATE_POPULAR_PLUGINS }}
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  slack:
    name: Slack
    needs: [jest, phpunit]
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v1
        with:
          type: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
