on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "!*"

name: CI

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    env:
      CI: 1
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci && bash travis-ci/bin/prepare.sh
      - name: Check code style
        run: bash travis-ci/bin/js/js-lint.sh
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    env:
      CI: 1
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci && bash travis-ci/bin/prepare.sh
      - name: Check code style
        run: bash travis-ci/bin/php/phpcs.sh
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    env:
      CI: 1
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci && bash travis-ci/bin/prepare.sh
      - name: Check code style
        run: bash travis-ci/bin/php/phpmd.sh
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  jest:
    name: Jest
    needs: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['8', '10', '11', '12']
    env:
      CI: 1
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci && bash travis-ci/bin/prepare.sh
      - name: Run tests
        run: bash travis-ci/bin/js/js-test.sh
      - name: Codecov
        run: curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f $COVERAGE_FILE
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COVERAGE_FILE: ./assets/js/coverage/lcov.info
        if: matrix.node == '12'
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
  phpunit:
    name: PHPUnit
    needs: [phpcs, phpmd]
    runs-on: ubuntu-16.04
    env:
      CI: 1
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
    services:
      mysql:
        image: mysql
        ports:
          - 3306
    strategy:
      matrix:
        php: ['7.0', '7.3', '5.6']
        WP_VERSION: ['latest', '5.2', '5.0']
        WP_MULTISITE: ['0', '1']
        include:
          - php: '7.3'
            WP_VERSION: 'latest'
            WP_MULTISITE: '1'
            ACTIVATE_POPULAR_PLUGINS: 1
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Switch PHP version
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: sudo ln -sf "/usr/bin/php$PHP_VERSION" /etc/alternatives/php
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci && bash travis-ci/bin/prepare.sh
        env:
          WP_VERSION: ${{ matrix.WP_VERSION }}
          WP_MULTISITE: ${{ matrix.WP_MULTISITE }}
          ACTIVATE_POPULAR_PLUGINS: ${{ matrix.ACTIVATE_POPULAR_PLUGINS }}
      - name: Run tests
        run: bash travis-ci/bin/php/wp-test.sh
        env:
          DB_PASS: root
          WP_VERSION: ${{ matrix.WP_VERSION }}
          WP_MULTISITE: ${{ matrix.WP_MULTISITE }}
          ACTIVATE_POPULAR_PLUGINS: ${{ matrix.ACTIVATE_POPULAR_PLUGINS }}
      - name: Codecov
        run: curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f $COVERAGE_FILE
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COVERAGE_FILE: ./coverage/clover.xml
        if: matrix.ACTIVATE_POPULAR_PLUGINS == 1
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  slack:
    name: Slack
    needs: [jest, phpunit]
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v1
        with:
          type: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
