on:
  issues:
    types: [opened]

name: Issue opened

jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Backlog
          COLUMN: To do

  assignAuthor:
    name: Assign author to issue
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1
