on:
  schedule:
    - cron: 0 17 * * 6
  pull_request:
    types: [opened, reopened, closed]
  repository_dispatch:
    types: [update-deps]

name: Update dependencies

env:
  CI: 1
  GITHUB_ACTION: 1
  TRAVIS_BUILD_DIR: ${{ github.workspace }}

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Update dependencies
        uses: technote-space/create-pr-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GLOBAL_INSTALL_PACKAGES: npm-check-updates
          EXECUTE_COMMANDS: |
            composer bin:download
            composer bin:update
          COMMIT_MESSAGE: 'chore: update dependencies'
          PR_BRANCH_NAME: 'chore-update-${PR_ID}'
          PR_TITLE: 'chore: update dependencies (${PR_MERGE_REF})'
          PR_DEFAULT_BRANCH_PREFIX: release/
          PR_DEFAULT_BRANCH_NAME: ${PATCH_VERSION}
          PR_DEFAULT_BRANCH_TITLE: release/${PATCH_VERSION}
          TARGET_BRANCH_PREFIX: release/
